server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=Asia/Seoul
    username: root
    password: Qwer1234!

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      show-sql: true
      format_sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true

    servlet:
      multipart:
        max-file-size: 10GB
        max-request-size: 10GB

mybatis:
  type-aliases-package: com.hongsam.hongflix.domain
  configuration:
    map-underscore-to-camel-case: true

cloud:
  aws:
    s3:
      bucket: woodyvideo
    credentials:
      access-key: AKIAZY5VWBZ6JG62JQNJ
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false